### ISSUE TITLE
Integrating with UI libraries

### ISSUE THREAD

**Issue by sadaqabdo** [bonafideduck/react-highlight-within-textarea#113]
I am trying to integrate this with TextField as shown in Mui [documentation](https://mui.com/components/text-fields/#integration-with-3rd-party-input-libraries), but it doesn't seem to highlight the words. Is there a way to render the highlighted words on top or within another component like Mui TextField?

```
const MyInputComponent = React.forwardRef((props, ref) => {
		const { component: Component, ...other } = props;
		React.useImperativeHandle(ref, () => ({
		  focus: () => {
			// logic to focus the rendered component from 3rd party belongs here
		  },
		  // hiding the value e.g. react-stripe-elements
		}));
		return <HighlightWithinTextarea 
		value={textValue}
		highlight={highlightsArray}
		onChange= {setTextValue}
		placeholder="Enter the text here"
		/>;
	  });
```
```
<TextField
                fullWidth
                label="sometext"
                placeholder="Enter the text here"
                value={textValue}
                onChange={(event) => {
	                setTextvalue(event.target.value);
                }}
                inputProps={{
	                inputcomponent: MyInputComponent,
	                inputprops: {
		                component: HighlightWithinTextarea
	                }
                }}
/>
```

**Comment by bonafideduck** [comment]
@sadaqabdo , I'm not certain what you are trying to do, but I've released 3.0.0-alpha that may have fixed some of the `ref` issues.

**Comment by Krak91** [comment]
Hey @sadaqabdo, have you managed to make this work? I'm trying to do the exact same thing where the text is highlighted inside the TextField but I'm very new to web design and struggling with this. If you could show me a working example I'd be grateful.

**Comment by sadaqabdo** [comment]
@Krak91, 
unfortunately, I haven't continued on trying to link it with MUI's TextField. However, I just used it in the normal way.
