### ISSUE TITLE
Offsets in long string

### ISSUE THREAD

**Issue by stylesuxx** [bonafideduck/react-highlight-within-textarea#16]
I have a long string, multiple lines long, no spaces and the marked elements seem to drift to the right (I am highlighting 32c2).
![Screenshot from 2021-03-27 22-18-23](https://user-images.githubusercontent.com/978192/112735191-c3c8ca00-8f4a-11eb-858d-b8a991c754f2.png)

Here is the string for  testing:
```
Melody:o=3,b=900,d=4:32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.,32c2#.,32d5#.
```

Edit:  Using a monospace font actually seems to help here...

**Comment by bonafideduck** [comment]
How annoying.  I'm sorry, but I probably won't be able to debug this any time soon.

**Comment by stylesuxx** [comment]
Don't worry, at least it is documented.

Again, my workaround was a monospace font, that made it better for whatever reason, maybe I am now just lucky because the marked portions don't break over a line.

**Comment by bonafideduck** [comment]
Version 2.0.0 should fix this.
