### ISSUE TITLE
draft.js error

### ISSUE THREAD

**Issue by wangdiee** [bonafideduck/react-highlight-within-textarea#173]
![image](https://user-images.githubusercontent.com/63644246/222693911-c2400802-97e0-4c98-81de-e52c44708ef4.png)

**Comment by bonafideduck** [comment]
I’ll update the documentation to say this has 3 `peerDependencies` that you must also install. 
 
`npm install draft-js react react-dom`

from package.json:
 
   ```
 "peerDependencies": {
    "draft-js": ">=0.11.7",
    "react": ">=0.14.0",
    "react-dom": ">=0.14.0"
  },
  ```
