### ISSUE TITLE
Long text performance

### ISSUE THREAD

**Issue by standbyoneself** [bonafideduck/react-highlight-within-textarea#175]
Hi there. Thank you for this library, it's really helpful.

But there is a performance issue because rerender is caused on every change event. It's a little bit annoying because our customers have to work with long text up to 50000 length.
Codesandbox: https://codesandbox.io/s/rhwta-string-forked-ngelzp?file=/src/App.js
 
If we are using native draft.js, it would rerender only span where change is happened.

Any plans on optimizing it? Maybe some tips or workarounds?

**Comment by standbyoneself** [comment]
We are really using ranges. We need to parse the boolean search query, build AST, grab the start/end positions of operators (AND, OR, NOT), not operands (WORD, PHRASE) and highlight those operators. Example of boolean search query: "github OR gitlab AND NOT bitbucket". Length of it may be few thousands symbols.

**Comment by standbyoneself** [comment]
@bonafideduck thanks for a reply. I have tested it locally with CPU throttling 6x on my MacBook Pro M1 Pro. In the first example input I have copy-paste your phrase "Potato potato tomato potato." in order to retrieve string up to 7000 length. After that I am trying to input "1", and it tooks approximately 150ms via React Profiler, which is 3x much faster than in the main branch (435ms), but still is not enough since the text length may be 50000. I have noticed that you rerender only the block that have been changed, but we need to inspect via DevTools why it tooks 150 ms for inserting one symbol

**Comment by bonafideduck** [comment]
@standbyoneself , I did an experiment with raw draftjs in [DraftPerf.tsx](https://github.com/bonafideduck/react-highlight-within-textarea/blob/issue-175/demo/src/DraftPerf.tsx) and unfortunately, that was only around 30% faster.  I was getting 283ms-497ms with my code and 202ms-375ms with raw draftjs.  So I'm running into diminishing returns on what I can do without trying to replace draft with quill (which would be version 4.0 of this code).

**Comment by standbyoneself** [comment]
@bonafideduck I understood. Do you have any approximate dates on releasing this useful library used quill.js?

**Comment by bonafideduck** [comment]
Unfortunately, it is no time soon.  I also don’t know if quill would be any more efficient.  If all you need to do is highlight certain words, you might consider using quill directly.

**Comment by standbyoneself** [comment]
Okay, I'll follow your projects.

**Comment by bonafideduck** [comment]
@standbyoneself , I have determined that quill will not be more performant than what is already available.  In fact it will be worse.  Check out this [demo](https://bonafideduck.github.io/react-highlight-within-textarea/#/quillPerf) for this [code](https://github.com/bonafideduck/react-highlight-within-textarea/blob/main/demo/src/QuillPerf.tsx).

**Comment by bonafideduck** [comment]
Also, the [draftPerformance](https://bonafideduck.github.io/react-highlight-within-textarea/#/draftPerf) seems to be pretty snappy when not debugging.
