### ISSUE TITLE
Clickable?

### ISSUE THREAD

**Issue by k2xl** [bonafideduck/react-highlight-within-textarea#19]
Feature request - be able to click on highlighted text (call a handler with the text clicked on passed in)

**Comment by bonafideduck** [comment]
This can be accomplished.  See “Custom Object with Enhancements” on the demo page. 

Unfortunately with the current design, the highlighting is behind the textarea and the only way to get informed is to have a z-index raising a clear box above.  But then mouse clicking to edit wont work.

**Comment by bonafideduck** [comment]
@k2xl, I have a preview of 2.0.0-alpha.8 available with [sample code](https://github.com/bonafideduck/react-highlight-within-textarea/tree/nwb-2-alpha/src) that should fix this.  It is published to NPM.

**Comment by bonafideduck** [comment]
Version 2.0.0 should fix this.
