### ISSUE TITLE
Scrolling textarea doesn't keep highlighting

### ISSUE THREAD

**Issue by k2xl** [bonafideduck/react-highlight-within-textarea#20]
In the demo page, if you type more text in the area it'll mess up the highlighting

**Comment by bonafideduck** [comment]
@k2xl please let me know if this is different from #16 and #17. Also, I have no immediate plans to fix this.  I may one day redo how the highlighting works (see comments in the other issues).

**Comment by bonafideduck** [comment]
@k2xl  , I have a complete rewrite that should fix this.  See 2.0.0-alpha.8 available with [sample code](https://github.com/bonafideduck/react-highlight-within-textarea/tree/nwb-2-alpha/src).

**Comment by bonafideduck** [comment]
Version 2.0.0 should fix this.
