### ISSUE TITLE
Which version of this are u using for the demo page? 

### ISSUE THREAD

**Issue by HBorah09** [bonafideduck/react-highlight-within-textarea#29]
I am using version 2.0.0-alpha.5 and trying to send array of positions in highlights. The behaviour is different from what I see in the demo page for line breaks.

**Comment by HBorah09** [comment]
I am using version 2.0.0-alpha.5 and trying to send array of positions in highlights. The behaviour is different from what I see in the demo page for line breaks.

**Comment by bonafideduck** [comment]
Use 1.01.  I apologise, I didnt realize npm would make alpha versions visible. 
I’m slowly getting the kinks out.

**Comment by bonafideduck** [comment]
@HBorah09 , the 1.0.2 version is doing ranges incorrectly.  I don't plan to fix it.  I have a preview of 2.0.0-alpha.8 available with [sample code](https://github.com/bonafideduck/react-highlight-within-textarea/tree/nwb-2-alpha/src).

**Comment by bonafideduck** [comment]
Version 2.0.0 works as documented.  1.0.2 is still broken and I have no plans to update it.

**Comment by HBorah09** [comment]
Great. Thanks
