### ISSUE TITLE
Forward ref to textarea from outside, Please!

### ISSUE THREAD

**Issue by miusuncle** [bonafideduck/react-highlight-within-textarea#30]
Forward ref to textarea from outside, Please!

**Comment by bonafideduck** [comment]
The 2.0 alpha build will allow this.  Unfortunately, development is going slowly.

**Comment by bonafideduck** [comment]
I have a preview of 2.0.0-alpha.8 available with [sample code](https://github.com/bonafideduck/react-highlight-within-textarea/tree/nwb-2-alpha/src).

This should change forward ref, but I haven't tested it.

**Comment by bonafideduck** [comment]
[preview](https://bonafideduck.github.io/rhwta-preview/)

**Comment by bonafideduck** [comment]
Version 2.0.0 should fix this.
