### ISSUE TITLE
Array of Two Numbers (Range) highlights on multiple rows, when new lines are used in the text

### ISSUE THREAD

**Issue by sandruen** [bonafideduck/react-highlight-within-textarea#39]
See your demo example on https://bonafideduck.github.io/react-highlight-within-textarea/  Array of Two Numbers (Range).

I have texts with new lines in between and the highlighting doesn't work correctly. For example passing an array with [0, 5] highlights on every row the chars on index [0, 5]. But we only want it to be highlighted once, in this example on the first row.
I saw, that for every new line a new div is created and the indexes of the highlights seem to start counting again from 0 for every div. Is this intended and is there a workaround for that?

Using regexes for our highlights is not an option, we need to use number arrays. 

<img width="736" alt="Bildschirmfoto 2021-07-07 um 12 19 15" src="https://user-images.githubusercontent.com/9726041/124742996-90b8ae00-df1d-11eb-9a40-2aa0e0b1fc34.png">

<img width="741" alt="Bildschirmfoto 2021-07-07 um 12 14 40" src="https://user-images.githubusercontent.com/9726041/124742370-ee002f80-df1c-11eb-979d-ad5aa23b0f6c.png">

**Comment by bonafideduck** [comment]
Well, that was unexpected. It is definitely a bug. 

This is the [range highlight code](https://github.com/bonafideduck/react-highlight-within-textarea/blob/fcfb80189bca8fb1bbdbccdc5c7f3b676ab59e51/src/highlightToCompositeDecorator.js#L92).  Draftjs must be sending each line in separately.  My guess is the fix will either be super easy or annoyingly difficult.

How soon do you need a fix?

**Comment by bonafideduck** [comment]
A quick look at what is available for the decorator doesn't give any indication that the second line is a second line.  So it looks like the fix will be annoyingly difficult.

**Comment by sandruen** [comment]
Thank you for your quick reply! 
We used version 0.9.12 in our application before and then upgraded to 2.0.0 as we were upgrading React to the latest version. Yesterday I managed to go back to version 1.0.0 which works with the latest React version, so we're fine for now.
Still it would be great to use version 2.0.0 eventually of course :).

**Comment by bonafideduck** [comment]
@sandruen I have published a fix with 2.1.0-beta.  I hope this solves your issues.

**Comment by sandruen** [comment]
Thank you!
