### ISSUE TITLE
Issues with editing the existing text 

### ISSUE THREAD

**Issue by dibe84** [bonafideduck/react-highlight-within-textarea#55]
Hello! I really love this feature! I just wanted to highlight a couple of small issues I face both with my app and with the online demo: https://bonafideduck.github.io/react-highlight-within-textarea/ 

- Try changing a character inside a word: seems that the character is added at the end of the word instead
- Try selecting  a whole line and delete it: seems that not the entire word is deleted

Are you planning to fix them? or Is there any workaround?

**Comment by bonafideduck** [comment]
I am not aware of this issue. I tried what you are doing on my iPad just now and couldnt reproduce it. What are you testing on?  Is it every demo or just certain ones?
