### ISSUE TITLE
Can we use tab or any hotkey to move around the highlighted text

### ISSUE THREAD

**Issue by shaan360** [bonafideduck/react-highlight-within-textarea#63]
Can we use a tab or any hotkey to move around the highlighted text?

**Comment by bonafideduck** [comment]
Not currently.  I may in the future expose most of the Draft.js editor properties including [handleKeyCommand](https://draftjs.org/docs/api-reference-editor#handlekeycommand) and you could implement such a capability.

**Comment by shaan360** [comment]
Thank you @bonafideduck  for the prompt reply. We will use it and will let you know if we are able to add this feature to it.

**Comment by bonafideduck** [comment]
@shaan360 , handleKeyCommand() is not yet exposed in RHWTA, but you can now directly use draftjs.  Check out “Unwrap and Use Draft.js Directly“ in https://bonafideduck.github.io/react-highlight-within-textarea/ .

**Comment by shaan360** [comment]
@bonafideduck thank you much appreciated.
